spring:
  application:
    name: sa-reminder-backend
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sa_reminder
    username: root
    password: 123456
  profiles:
    active: local
  mail:
    host: smtp.163.com
    username: allexu@163.com
    password: EYmam342Hpt9vy6C
    default-encoding: UTF-8
  properties:
    mail:
      smtp:
        auth: true
server:
  port: 8080
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: default
      packages-to-scan: com.workspace.sareminderbackend.controller
#knife4j
knife4j:
  enable: true
  setting:
    language: zh-CN
# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
