spring:
  application:
    name: sa-reminder-backend
server:
  port: 8080
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: default
      packages-to-scan: com.workspace.sareminderbackend.controller
#knife4j
knife4j:
  enable: true
  setting:
    language: zh-CN
